language: python
python:
- 2.6
- 2.7
- 3.4
- 3.5
- 3.6
- pypy
- pypy3
install:
- python -c 'import importlib' 2>/dev/null || pip install importlib
script:
- python setup.py test
notifications:
  irc:
    channels:
    - "irc.ozinger.org#hangulize"
    on_success: change
    on_failure: always
